/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fixya;

import javax.swing.JOptionPane;

/**
 *
 * @author estebanpardo
 */
public class AgregarTrabajoOrdenFrame extends javax.swing.JFrame {
    private OrdenDAO ordenDAO;
    private TrabajoDAO trabajoDAO;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarTrabajoOrdenFrame.class.getName());

    /**
     * Creates new form AgregarTrabajoOrdenFrame
     */
    public AgregarTrabajoOrdenFrame() {
        this.ordenDAO = new OrdenDAO();
        this.trabajoDAO = new TrabajoDAO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        descripcionField = new javax.swing.JTextField();
        costoField = new javax.swing.JTextField();
        chapaField = new javax.swing.JTextField();
        idOrdenField = new javax.swing.JTextField();
        buscarOrden = new javax.swing.JButton();
        agregarTrabajoBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordenesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descripcionField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(descripcionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 290, 70));

        costoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(costoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 210, 40));

        chapaField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chapaField.setToolTipText("");
        chapaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chapaFieldActionPerformed(evt);
            }
        });
        jPanel1.add(chapaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 190, 40));

        idOrdenField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(idOrdenField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 280, 40));

        buscarOrden.setBackground(new java.awt.Color(51, 102, 255));
        buscarOrden.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        buscarOrden.setForeground(new java.awt.Color(255, 255, 255));
        buscarOrden.setText("Buscar Orden");
        buscarOrden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarOrden.setBorderPainted(false);
        buscarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarOrdenActionPerformed(evt);
            }
        });
        jPanel1.add(buscarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 180, 40));

        agregarTrabajoBtn.setBackground(new java.awt.Color(51, 102, 255));
        agregarTrabajoBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        agregarTrabajoBtn.setForeground(new java.awt.Color(255, 255, 255));
        agregarTrabajoBtn.setText("Agregar Trabajo ");
        agregarTrabajoBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agregarTrabajoBtn.setBorderPainted(false);
        agregarTrabajoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTrabajoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(agregarTrabajoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 220, 50));

        volverBtn.setBackground(new java.awt.Color(102, 102, 102));
        volverBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        jScrollPane1.setViewportView(ordenesTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 300, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar Trabajo Orden.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
        new MenuOrdenesFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void buscarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarOrdenActionPerformed
        // TODO add your handling code here:
        buscarOrden();
    }//GEN-LAST:event_buscarOrdenActionPerformed

    private void agregarTrabajoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTrabajoBtnActionPerformed
        // TODO add your handling code here:
        agregarTrabajoOrden();
    }//GEN-LAST:event_agregarTrabajoBtnActionPerformed

    private void chapaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chapaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chapaFieldActionPerformed

    private void buscarOrden(){
        String chapa = chapaField.getText().toUpperCase().replace(" ", "").trim();
        ordenDAO.buscarOrdenSimple(chapa,ordenesTable);
    }
    
    private void agregarTrabajoOrden(){
        String idString = idOrdenField.getText().trim();
        String descripcion = descripcionField.getText().trim();
        String costoString = costoField.getText().trim();
        if (idString.isEmpty() || descripcion.isEmpty() || costoString.isEmpty()){
            JOptionPane.showMessageDialog(this, "Completa todos los campos para agregar el trabajo a la orden", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            int idOrden = Integer.parseInt(idString);
            double costo = Double.parseDouble(costoString);
            Trabajo trabajo = new Trabajo(descripcion,costo);
            boolean trabajoAgregado = trabajoDAO.insertarTrabajo(idOrden, trabajo);
            if (trabajoAgregado) {
                JOptionPane.showMessageDialog(this, "Trabajo agregado correctamente");
                new MenuOrdenesFrame().setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(this, "El trabajo no se ha podido agregar");
                new MenuOrdenesFrame().setVisible(true);
                dispose();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AgregarTrabajoOrdenFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarTrabajoBtn;
    private javax.swing.JButton buscarOrden;
    private javax.swing.JTextField chapaField;
    private javax.swing.JTextField costoField;
    private javax.swing.JTextField descripcionField;
    private javax.swing.JTextField idOrdenField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ordenesTable;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
