/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fixya;

/**
 *
 * @author estebanpardo
 */
public class BuscarOrdenFrame extends javax.swing.JFrame {
    private OrdenDAO ordenDAO = new OrdenDAO();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuscarOrdenFrame.class.getName());

    /**
     * Creates new form BuscarOrdenFrame
     */
    public BuscarOrdenFrame() {
        this.ordenDAO = ordenDAO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        volverBtn = new javax.swing.JButton();
        buscarOrdenBtn = new javax.swing.JButton();
        chapaField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordenesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverBtn.setBackground(new java.awt.Color(102, 102, 102));
        volverBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        bg.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        buscarOrdenBtn.setBackground(new java.awt.Color(51, 102, 255));
        buscarOrdenBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        buscarOrdenBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarOrdenBtn.setText("Buscar Orden ");
        buscarOrdenBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarOrdenBtn.setBorderPainted(false);
        buscarOrdenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarOrdenBtnActionPerformed(evt);
            }
        });
        bg.add(buscarOrdenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 220, 50));

        chapaField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chapaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chapaFieldActionPerformed(evt);
            }
        });
        bg.add(chapaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 390, 60));

        jScrollPane1.setViewportView(ordenesTable);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 281, 530, 220));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuscarOrden (1).png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
        new MenuOrdenesFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void buscarOrdenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarOrdenBtnActionPerformed
        // TODO add your handling code here:
        buscarOrden();
    }//GEN-LAST:event_buscarOrdenBtnActionPerformed

    private void chapaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chapaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chapaFieldActionPerformed
    
    private void buscarOrden(){
        String chapa = chapaField.getText();
        ordenDAO.buscarOrden(chapa, ordenesTable);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BuscarOrdenFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton buscarOrdenBtn;
    private javax.swing.JTextField chapaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ordenesTable;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
