package com.mycompany.fixya;

import javax.swing.JOptionPane;

public class CambiarEstadoOrdenFrame extends javax.swing.JFrame {
    private OrdenDAO ordenDAO;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CambiarEstadoOrdenFrame.class.getName());

    /**
     * Creates new form CambiarEstadoOrdenFrame
     */
    public CambiarEstadoOrdenFrame() {
        this.ordenDAO = new OrdenDAO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        volverBtn = new javax.swing.JButton();
        ordenIdField = new javax.swing.JTextField();
        buscarOrdenBtn = new javax.swing.JButton();
        estadosComboBox = new javax.swing.JComboBox<>();
        chapaField = new javax.swing.JTextField();
        cambiarEstadoOrdenBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordenesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverBtn.setBackground(new java.awt.Color(102, 102, 102));
        volverBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        ordenIdField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ordenIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenIdFieldActionPerformed(evt);
            }
        });
        jPanel1.add(ordenIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 180, 40));

        buscarOrdenBtn.setBackground(new java.awt.Color(51, 102, 255));
        buscarOrdenBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        buscarOrdenBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarOrdenBtn.setText("Buscar orden");
        buscarOrdenBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarOrdenBtn.setBorderPainted(false);
        buscarOrdenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarOrdenBtnActionPerformed(evt);
            }
        });
        jPanel1.add(buscarOrdenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 160, 40));

        estadosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espera", "Proceso", "Terminada" }));
        estadosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadosComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(estadosComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 210, 40));

        chapaField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chapaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chapaFieldActionPerformed(evt);
            }
        });
        jPanel1.add(chapaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 180, 40));

        cambiarEstadoOrdenBtn.setBackground(new java.awt.Color(51, 102, 255));
        cambiarEstadoOrdenBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        cambiarEstadoOrdenBtn.setForeground(new java.awt.Color(255, 255, 255));
        cambiarEstadoOrdenBtn.setText("Cambiar estado");
        cambiarEstadoOrdenBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cambiarEstadoOrdenBtn.setBorderPainted(false);
        cambiarEstadoOrdenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarEstadoOrdenBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cambiarEstadoOrdenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 220, 50));

        jScrollPane1.setViewportView(ordenesTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 310, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Agregar Trabajo Orden (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
        new MenuOrdenesFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void buscarOrdenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarOrdenBtnActionPerformed
        // TODO add your handling code here:
        buscarOrden();
    }//GEN-LAST:event_buscarOrdenBtnActionPerformed

    private void ordenIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordenIdFieldActionPerformed

    private void estadosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadosComboBoxActionPerformed

    private void chapaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chapaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chapaFieldActionPerformed

    private void cambiarEstadoOrdenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarEstadoOrdenBtnActionPerformed
        // TODO add your handling code here:
        cambiarEstadoOrden();
    }//GEN-LAST:event_cambiarEstadoOrdenBtnActionPerformed
    private void buscarOrden(){
    String chapa = chapaField.getText().toUpperCase().replace(" ", "").trim();
    ordenDAO.buscarOrdenSimple(chapa, ordenesTable);
}
    private void cambiarEstadoOrden(){
        String ordenIdString = ordenIdField.getText().trim();
        int opcionEstado = estadosComboBox.getSelectedIndex() + 1;
        if (ordenIdString.isEmpty()){
            JOptionPane.showMessageDialog(this, "Completa con el N° de Orden para cambiar el estado", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if (opcionEstado==1){
                int ordenId = Integer.parseInt(ordenIdString);
                boolean cambio = ordenDAO.cambiarEstadoOrden(ordenId,opcionEstado);
                if (cambio) {
                JOptionPane.showMessageDialog(this, "La orden se cambio a 'Espera' ");
                new MenuOrdenesFrame().setVisible(true);
                dispose();
                }else{
                JOptionPane.showMessageDialog(this, "No se ha podido cambiar el estado de la orden");
                new MenuOrdenesFrame().setVisible(true);
                dispose();
                }
            }else if (opcionEstado==2){
                int ordenId = Integer.parseInt(ordenIdString);
                boolean cambio = ordenDAO.cambiarEstadoOrden(ordenId, opcionEstado);
                if (cambio) {
                JOptionPane.showMessageDialog(this, "La orden se cambio a 'Proceso' ");
                new MenuOrdenesFrame().setVisible(true);
                dispose();
                }else{
                JOptionPane.showMessageDialog(this, "No se ha podido cambiar el estado de la orden");
                new MenuOrdenesFrame().setVisible(true);
                dispose();
                }
            }else if (opcionEstado==3){
            int ordenId = Integer.parseInt(ordenIdString);
            boolean cambio = ordenDAO.cambiarEstadoOrden(ordenId, opcionEstado);
            ordenDAO.cerrarOrden(ordenId);
                if (cambio) {
                JOptionPane.showMessageDialog(this, "La orden se cambio a 'Terminada' ");
                new MenuOrdenesFrame().setVisible(true);
                dispose();
                }else{
                JOptionPane.showMessageDialog(this, "No se ha podido cambiar el estado de la orden");
                new MenuOrdenesFrame().setVisible(true);
                dispose();
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CambiarEstadoOrdenFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarOrdenBtn;
    private javax.swing.JButton cambiarEstadoOrdenBtn;
    private javax.swing.JTextField chapaField;
    private javax.swing.JComboBox<String> estadosComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ordenIdField;
    private javax.swing.JTable ordenesTable;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
