/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fixya;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author estebanpardo
 */
public class CrearVehiculoFrame extends javax.swing.JFrame {
    private JFrame MenuVehiculoFrame;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearVehiculoFrame.class.getName());

    /**
     * Creates new form CrearVehiculoFrame
     */
    public CrearVehiculoFrame() {
        this.MenuVehiculoFrame = new MenuVehiculoFrame();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        volverBtn = new javax.swing.JButton();
        fabricanteField = new javax.swing.JTextField();
        modeloField = new javax.swing.JTextField();
        anioField = new javax.swing.JTextField();
        chapaField = new javax.swing.JTextField();
        dniField = new javax.swing.JTextField();
        registrarVehiculoBtn = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverBtn.setBackground(new java.awt.Color(102, 102, 102));
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        bg.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        fabricanteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fabricanteFieldActionPerformed(evt);
            }
        });
        bg.add(fabricanteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 380, 50));

        modeloField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloFieldActionPerformed(evt);
            }
        });
        bg.add(modeloField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 380, 50));
        bg.add(anioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 380, 50));
        bg.add(chapaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 380, 50));

        dniField.setToolTipText("");
        bg.add(dniField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 380, 50));

        registrarVehiculoBtn.setBackground(new java.awt.Color(51, 102, 255));
        registrarVehiculoBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        registrarVehiculoBtn.setForeground(new java.awt.Color(255, 255, 255));
        registrarVehiculoBtn.setText("Registrar Vehículo");
        registrarVehiculoBtn.setBorderPainted(false);
        registrarVehiculoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVehiculoBtnActionPerformed(evt);
            }
        });
        bg.add(registrarVehiculoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 220, 50));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RegistrarVehiculo.png"))); // NOI18N
        bg.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fabricanteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fabricanteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fabricanteFieldActionPerformed

    private void modeloFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloFieldActionPerformed

    private void registrarVehiculoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVehiculoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarVehiculoBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
        MenuVehiculoFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearVehiculoFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anioField;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField chapaField;
    private javax.swing.JTextField dniField;
    private javax.swing.JTextField fabricanteField;
    private javax.swing.JLabel imagen;
    private javax.swing.JTextField modeloField;
    private javax.swing.JButton registrarVehiculoBtn;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
