/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fixya;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Tote
 */
public class CrearClienteFrame extends javax.swing.JFrame {
    private JFrame CrearClienteFrame;
    private ClienteDAO clienteDAO;

    /**
     * Creates new form CrearClienteFrame
     */
    public CrearClienteFrame() {
        initComponents();
        this.CrearClienteFrame=CrearClienteFrame;
        clienteDAO = new ClienteDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        ApellidoField = new javax.swing.JTextField();
        CorreoField = new javax.swing.JTextField();
        TelefonoField = new javax.swing.JTextField();
        CrearClienteBtn = new javax.swing.JButton();
        DNIField = new javax.swing.JTextField();
        NombreTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(0, 102, 204));
        bg.setPreferredSize(new java.awt.Dimension(700, 400));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ApellidoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(ApellidoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 370, 40));

        CorreoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CorreoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoFieldActionPerformed(evt);
            }
        });
        bg.add(CorreoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 370, 40));

        TelefonoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TelefonoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoFieldActionPerformed(evt);
            }
        });
        bg.add(TelefonoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 370, 40));

        CrearClienteBtn.setBackground(new java.awt.Color(51, 102, 255));
        CrearClienteBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CrearClienteBtn.setForeground(new java.awt.Color(255, 255, 255));
        CrearClienteBtn.setText("Crear");
        CrearClienteBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CrearClienteBtn.setBorderPainted(false);
        CrearClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearClienteBtnActionPerformed(evt);
            }
        });
        bg.add(CrearClienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 220, 50));

        DNIField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DNIField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNIFieldActionPerformed(evt);
            }
        });
        bg.add(DNIField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 370, 40));

        NombreTxtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtFieldActionPerformed(evt);
            }
        });
        bg.add(NombreTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 370, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CrearClientes.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CorreoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoFieldActionPerformed

    private void TelefonoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoFieldActionPerformed

    private void CrearClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearClienteBtnActionPerformed
        // TODO add your handling code here:
        registrarCliente();
    }//GEN-LAST:event_CrearClienteBtnActionPerformed

    private void DNIFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNIFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNIFieldActionPerformed

    private void NombreTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtFieldActionPerformed
    private void registrarCliente(){
        String nombre = NombreTxtField.getText();
        String apellido = ApellidoField.getText();
        String correo = CorreoField.getText();
        String telefono = TelefonoField.getText();
        String DNIString = DNIField.getText();
        int DNI = Integer.parseInt(DNIString);
        Cliente cliente = new Cliente(nombre,apellido,correo,telefono,DNI);
        boolean insertarCliente = clienteDAO.insertarCliente(cliente);
        if (insertarCliente) {
            JOptionPane.showMessageDialog(this, "Cliente registrado correctamente");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearClienteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoField;
    private javax.swing.JTextField CorreoField;
    private javax.swing.JButton CrearClienteBtn;
    private javax.swing.JTextField DNIField;
    private javax.swing.JTextField NombreTxtField;
    private javax.swing.JTextField TelefonoField;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
