/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fixya;

import javax.swing.JOptionPane;

/**
 *
 * @author estebanpardo
 */
public class CrearOrdenFrame extends javax.swing.JFrame {
    private OrdenDAO ordenDAO;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearOrdenFrame.class.getName());

    /**
     * Creates new form CrearOrdenFrame
     */
    public CrearOrdenFrame() {
        this.ordenDAO = new OrdenDAO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chapaField = new javax.swing.JTextField();
        volverBtn = new javax.swing.JButton();
        crearOrdenBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(chapaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 390, 50));

        volverBtn.setBackground(new java.awt.Color(102, 102, 102));
        volverBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        crearOrdenBtn.setBackground(new java.awt.Color(51, 102, 255));
        crearOrdenBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        crearOrdenBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearOrdenBtn.setText("Crear Orden");
        crearOrdenBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crearOrdenBtn.setBorderPainted(false);
        crearOrdenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearOrdenBtnActionPerformed(evt);
            }
        });
        jPanel1.add(crearOrdenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 220, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_CrearOrden .png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
        new MenuOrdenesFrame().setVisible(true);
        dispose();
       
    }//GEN-LAST:event_volverBtnActionPerformed

    private void crearOrdenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearOrdenBtnActionPerformed
        // TODO add your handling code here:
        crearOrden();
   
    }//GEN-LAST:event_crearOrdenBtnActionPerformed

    private void crearOrden(){
        String chapa = chapaField.getText().toUpperCase().replace(" ", "").trim();
        boolean ordenCreada = ordenDAO.insertarOrden(chapa);
        if (ordenCreada){
        JOptionPane.showMessageDialog(this, "Orden creada correctamente");
            new MenuOrdenesFrame().setVisible(true);
            dispose();
    }else{
        JOptionPane.showMessageDialog(this, "La orden no se pudo crear", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearOrdenFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chapaField;
    private javax.swing.JButton crearOrdenBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
