/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fixya;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Tote
 */
public class CrearClienteFrame extends javax.swing.JFrame {
    private JFrame CrearClienteFrame;
    private ClienteDAO clienteDAO;

    /**
     * Creates new form CrearClienteFrame
     */
    public CrearClienteFrame() {
        initComponents();
        this.CrearClienteFrame=CrearClienteFrame;
        clienteDAO = new ClienteDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Header = new javax.swing.JLabel();
        NombreField = new javax.swing.JTextField();
        PanelNombre = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        PanelApellido = new javax.swing.JPanel();
        Apellido = new javax.swing.JLabel();
        ApellidoField = new javax.swing.JTextField();
        PanelCorreo = new javax.swing.JPanel();
        Correo = new javax.swing.JLabel();
        CorreoField = new javax.swing.JTextField();
        PanelTelefono = new javax.swing.JPanel();
        Telefono = new javax.swing.JLabel();
        TelefonoField = new javax.swing.JTextField();
        CrearClienteBtn = new javax.swing.JButton();
        PanelDNI = new javax.swing.JPanel();
        DNI = new javax.swing.JLabel();
        DNIField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(0, 102, 204));
        bg.setPreferredSize(new java.awt.Dimension(700, 400));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CreacClienteLogo.png"))); // NOI18N
        Header.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bg.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 350, 50));

        NombreField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreFieldActionPerformed(evt);
            }
        });
        bg.add(NombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 190, 40));

        PanelNombre.setBackground(new java.awt.Color(153, 204, 255));

        Nombre.setBackground(new java.awt.Color(153, 204, 255));
        Nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre");

        javax.swing.GroupLayout PanelNombreLayout = new javax.swing.GroupLayout(PanelNombre);
        PanelNombre.setLayout(PanelNombreLayout);
        PanelNombreLayout.setHorizontalGroup(
            PanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNombreLayout.setVerticalGroup(
            PanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        bg.add(PanelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, 40));

        PanelApellido.setBackground(new java.awt.Color(153, 204, 255));

        Apellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Apellido.setForeground(new java.awt.Color(0, 0, 0));
        Apellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Apellido.setText("Apellido");

        javax.swing.GroupLayout PanelApellidoLayout = new javax.swing.GroupLayout(PanelApellido);
        PanelApellido.setLayout(PanelApellidoLayout);
        PanelApellidoLayout.setHorizontalGroup(
            PanelApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelApellidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PanelApellidoLayout.setVerticalGroup(
            PanelApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelApellidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Apellido)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        bg.add(PanelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 40));

        ApellidoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(ApellidoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, 40));

        PanelCorreo.setBackground(new java.awt.Color(153, 204, 255));

        Correo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Correo.setForeground(new java.awt.Color(0, 0, 0));
        Correo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Correo.setText("Correo electronico ");

        javax.swing.GroupLayout PanelCorreoLayout = new javax.swing.GroupLayout(PanelCorreo);
        PanelCorreo.setLayout(PanelCorreoLayout);
        PanelCorreoLayout.setHorizontalGroup(
            PanelCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCorreoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Correo)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        PanelCorreoLayout.setVerticalGroup(
            PanelCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCorreoLayout.createSequentialGroup()
                .addComponent(Correo)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        bg.add(PanelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 220, 40));

        CorreoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CorreoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoFieldActionPerformed(evt);
            }
        });
        bg.add(CorreoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 220, 40));

        PanelTelefono.setBackground(new java.awt.Color(153, 204, 255));

        Telefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Telefono.setForeground(new java.awt.Color(0, 0, 0));
        Telefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Telefono.setText("Teléfono");

        javax.swing.GroupLayout PanelTelefonoLayout = new javax.swing.GroupLayout(PanelTelefono);
        PanelTelefono.setLayout(PanelTelefonoLayout);
        PanelTelefonoLayout.setHorizontalGroup(
            PanelTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTelefonoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Telefono)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        PanelTelefonoLayout.setVerticalGroup(
            PanelTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTelefonoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Telefono)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bg.add(PanelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 220, 50));

        TelefonoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TelefonoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoFieldActionPerformed(evt);
            }
        });
        bg.add(TelefonoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 220, 40));

        CrearClienteBtn.setBackground(new java.awt.Color(153, 204, 255));
        CrearClienteBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CrearClienteBtn.setForeground(new java.awt.Color(0, 0, 0));
        CrearClienteBtn.setText("Crear");
        CrearClienteBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CrearClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearClienteBtnActionPerformed(evt);
            }
        });
        bg.add(CrearClienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 160, 40));

        PanelDNI.setBackground(new java.awt.Color(153, 204, 255));

        DNI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DNI.setForeground(new java.awt.Color(0, 0, 0));
        DNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DNI.setText("DNI");

        javax.swing.GroupLayout PanelDNILayout = new javax.swing.GroupLayout(PanelDNI);
        PanelDNI.setLayout(PanelDNILayout);
        PanelDNILayout.setHorizontalGroup(
            PanelDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDNILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DNI)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDNILayout.setVerticalGroup(
            PanelDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDNILayout.createSequentialGroup()
                .addComponent(DNI)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        bg.add(PanelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 140, 40));

        DNIField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DNIField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNIFieldActionPerformed(evt);
            }
        });
        bg.add(DNIField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreFieldActionPerformed

    private void CorreoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoFieldActionPerformed

    private void TelefonoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoFieldActionPerformed

    private void CrearClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearClienteBtnActionPerformed
        // TODO add your handling code here:
        registrarCliente();
    }//GEN-LAST:event_CrearClienteBtnActionPerformed

    private void DNIFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNIFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNIFieldActionPerformed
    private void registrarCliente(){
        String nombre = NombreField.getText();
        String apellido = ApellidoField.getText();
        String correo = CorreoField.getText();
        String telefono = TelefonoField.getText();
        String DNIString = DNIField.getText();
        int DNI = Integer.parseInt(DNIString);
        Cliente cliente = new Cliente(nombre,apellido,correo,telefono,DNI);
        boolean insertarCliente = clienteDAO.insertarCliente(cliente);
        if (insertarCliente) {
            JOptionPane.showMessageDialog(this, "Cliente registrado correctamente");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearClienteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JTextField ApellidoField;
    private javax.swing.JLabel Correo;
    private javax.swing.JTextField CorreoField;
    private javax.swing.JButton CrearClienteBtn;
    private javax.swing.JLabel DNI;
    private javax.swing.JTextField DNIField;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreField;
    private javax.swing.JPanel PanelApellido;
    private javax.swing.JPanel PanelCorreo;
    private javax.swing.JPanel PanelDNI;
    private javax.swing.JPanel PanelNombre;
    private javax.swing.JPanel PanelTelefono;
    private javax.swing.JLabel Telefono;
    private javax.swing.JTextField TelefonoField;
    private javax.swing.JPanel bg;
    // End of variables declaration//GEN-END:variables
}
