package com.mycompany.fixya;

import javax.swing.*;

public class CrearCuentaFrame extends JFrame {
    private JFrame InicioSesionFrame;
    private Autenticacion auth;
    /**
     * Creates new form CrearCuenta
     */
    public CrearCuentaFrame() {
        auth = new Autenticacion();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        apellidoField = new javax.swing.JTextField();
        telefonoField = new javax.swing.JTextField();
        correoField = new javax.swing.JTextField();
        nombreField = new javax.swing.JTextField();
        contrasenaPasswordField = new javax.swing.JPasswordField();
        nombreUsuarioField = new javax.swing.JTextField();
        volverBtn = new javax.swing.JButton();
        crearCuentaBtn = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(700, 400));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        apellidoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellidoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoFieldActionPerformed(evt);
            }
        });
        bg.add(apellidoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 290, 50));

        telefonoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(telefonoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 290, 50));

        correoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(correoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 290, 50));

        nombreField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(nombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 290, 50));

        contrasenaPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(contrasenaPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 523, 290, 50));

        nombreUsuarioField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(nombreUsuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 290, 50));

        volverBtn.setBackground(new java.awt.Color(0, 51, 255));
        volverBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("Volver");
        volverBtn.setToolTipText("");
        volverBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        volverBtn.setBorderPainted(false);
        volverBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volverBtnMousePressed(evt);
            }
        });
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        bg.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 180, 40));

        crearCuentaBtn.setBackground(new java.awt.Color(0, 51, 255));
        crearCuentaBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        crearCuentaBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearCuentaBtn.setText("Crear cuenta");
        crearCuentaBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crearCuentaBtn.setBorderPainted(false);
        crearCuentaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearCuentaBtnMousePressed(evt);
            }
        });
        crearCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaBtnActionPerformed(evt);
            }
        });
        bg.add(crearCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 180, 40));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CrearCuenta.png"))); // NOI18N
        bg.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverBtnMousePressed
        // TODO add your handling code here:
            new InicioSesionFrame().setVisible(true);
            dispose();
    }//GEN-LAST:event_volverBtnMousePressed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
            new InicioSesionFrame().setVisible(true);
            dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void crearCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearCuentaBtnActionPerformed

    private void crearCuentaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearCuentaBtnMousePressed
        // TODO add your handling code here:
        registrarUsuario();
    }//GEN-LAST:event_crearCuentaBtnMousePressed

    private void apellidoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoFieldActionPerformed
    private void registrarUsuario() {
        String nombre = nombreUsuarioField.getText();
        String apellido = apellidoField.getText();
        String correo = correoField.getText();
        String telefono = telefonoField.getText();
        String nombreUsuario = nombreUsuarioField.getText();
        String contrasena = new String(contrasenaPasswordField.getPassword());

        boolean creado = auth.registrarUsuario(nombre, apellido, correo, telefono, nombreUsuario, contrasena);
        if (creado) {
            JOptionPane.showMessageDialog(this, "Usuario registrado correctamente");
            new InicioSesionFrame().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuentaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoField;
    private javax.swing.JPanel bg;
    private javax.swing.JPasswordField contrasenaPasswordField;
    private javax.swing.JTextField correoField;
    private javax.swing.JButton crearCuentaBtn;
    private javax.swing.JLabel imagen;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField nombreUsuarioField;
    private javax.swing.JTextField telefonoField;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
