package com.mycompany.fixya;

import javax.swing.*;

public class CrearCuentaFrame extends JFrame {
    private JFrame InicioSesionFrame;
    private Autenticacion auth;
    /**
     * Creates new form CrearCuenta
     */
    public CrearCuentaFrame() {
        this.InicioSesionFrame = InicioSesionFrame;
        auth = new Autenticacion();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        ApellidoField = new javax.swing.JTextField();
        TelefonoField = new javax.swing.JTextField();
        CorreoField = new javax.swing.JTextField();
        NombreField = new javax.swing.JTextField();
        ContrasenaField = new javax.swing.JPasswordField();
        NombreUsuarioField = new javax.swing.JTextField();
        VolverBtn = new javax.swing.JButton();
        CrearCuentaBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(700, 400));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ApellidoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ApellidoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoFieldActionPerformed(evt);
            }
        });
        background.add(ApellidoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 290, 50));

        TelefonoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        background.add(TelefonoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 290, 50));

        CorreoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        background.add(CorreoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 290, 50));

        NombreField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        background.add(NombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 290, 50));

        ContrasenaField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        background.add(ContrasenaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 523, 290, 50));

        NombreUsuarioField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        background.add(NombreUsuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 290, 50));

        VolverBtn.setBackground(new java.awt.Color(0, 51, 255));
        VolverBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        VolverBtn.setForeground(new java.awt.Color(255, 255, 255));
        VolverBtn.setText("Volver");
        VolverBtn.setToolTipText("");
        VolverBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VolverBtn.setBorderPainted(false);
        VolverBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VolverBtnMousePressed(evt);
            }
        });
        VolverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBtnActionPerformed(evt);
            }
        });
        background.add(VolverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 180, 40));

        CrearCuentaBtn.setBackground(new java.awt.Color(0, 51, 255));
        CrearCuentaBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        CrearCuentaBtn.setForeground(new java.awt.Color(255, 255, 255));
        CrearCuentaBtn.setText("Crear cuenta");
        CrearCuentaBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CrearCuentaBtn.setBorderPainted(false);
        CrearCuentaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CrearCuentaBtnMousePressed(evt);
            }
        });
        CrearCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCuentaBtnActionPerformed(evt);
            }
        });
        background.add(CrearCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CrearCuenta.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverBtnMousePressed
        // TODO add your handling code here:
            InicioSesionFrame.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_VolverBtnMousePressed

    private void VolverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBtnActionPerformed
        // TODO add your handling code here:
            InicioSesionFrame.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_VolverBtnActionPerformed

    private void CrearCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCuentaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearCuentaBtnActionPerformed

    private void CrearCuentaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCuentaBtnMousePressed
        // TODO add your handling code here:
        registrarUsuario();
    }//GEN-LAST:event_CrearCuentaBtnMousePressed

    private void ApellidoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoFieldActionPerformed
    private void registrarUsuario() {
        String nombre = NombreUsuarioField.getText();
        String apellido = ApellidoField.getText();
        String correo = CorreoField.getText();
        String telefono = TelefonoField.getText();
        String nombreUsuario = NombreUsuarioField.getText();
        String contrasena = new String(ContrasenaField.getPassword());

        boolean creado = auth.registrarUsuario(nombre, apellido, correo, telefono, nombreUsuario, contrasena);
        if (creado) {
            JOptionPane.showMessageDialog(this, "Usuario registrado correctamente");
            if (InicioSesionFrame != null) InicioSesionFrame.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuentaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoField;
    private javax.swing.JPasswordField ContrasenaField;
    private javax.swing.JTextField CorreoField;
    private javax.swing.JButton CrearCuentaBtn;
    private javax.swing.JTextField NombreField;
    private javax.swing.JTextField NombreUsuarioField;
    private javax.swing.JTextField TelefonoField;
    private javax.swing.JButton VolverBtn;
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
