package com.mycompany.fixya;

import javax.swing.*;

public class InicioSesionFrame extends JFrame {
    private Autenticacion auth;
    private JFrame CrearCuentaFrame;
    /**
     * Creates new form InicioSesion
     */
    public InicioSesionFrame() {
        this.CrearCuentaFrame = CrearCuentaFrame;
        auth = new Autenticacion();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        contrasenaPasswordField = new javax.swing.JPasswordField();
        crearCuentaBtn = new javax.swing.JButton();
        nombreUsuarioField = new javax.swing.JTextField();
        iniciarSesionBtn = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(700, 400));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contrasenaPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contrasenaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaPasswordFieldActionPerformed(evt);
            }
        });
        bg.add(contrasenaPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 290, 50));

        crearCuentaBtn.setBackground(new java.awt.Color(51, 51, 255));
        crearCuentaBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        crearCuentaBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearCuentaBtn.setText("Crear cuenta");
        crearCuentaBtn.setToolTipText("");
        crearCuentaBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crearCuentaBtn.setBorderPainted(false);
        crearCuentaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearCuentaBtnMousePressed(evt);
            }
        });
        crearCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaBtnActionPerformed(evt);
            }
        });
        bg.add(crearCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 220, 50));

        nombreUsuarioField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreUsuarioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioFieldActionPerformed(evt);
            }
        });
        bg.add(nombreUsuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 290, 50));

        iniciarSesionBtn.setBackground(new java.awt.Color(51, 51, 255));
        iniciarSesionBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        iniciarSesionBtn.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSesionBtn.setText("Iniciar sesión");
        iniciarSesionBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        iniciarSesionBtn.setBorderPainted(false);
        iniciarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionBtnActionPerformed(evt);
            }
        });
        bg.add(iniciarSesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 220, 50));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IniciarSesion.png"))); // NOI18N
        bg.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionBtnActionPerformed
        // TODO add your handling code here:
        realizarLogin();
    }//GEN-LAST:event_iniciarSesionBtnActionPerformed

    private void crearCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearCuentaBtnActionPerformed

    private void crearCuentaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearCuentaBtnMousePressed
        // TODO add your handling code here:
        CrearCuentaFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_crearCuentaBtnMousePressed

    private void nombreUsuarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioFieldActionPerformed

    private void contrasenaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaPasswordFieldActionPerformed
    private void realizarLogin() {
        String usuario = nombreUsuarioField.getText();
        String contrasena = new String(contrasenaPasswordField.getPassword());

        Usuario u = auth.iniciarSesion(usuario, contrasena);
        if (u != null) {
            JOptionPane.showMessageDialog(this, "Bienvenido " + u.getNombre());
            new MenuPrincipalFrame().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPasswordField contrasenaPasswordField;
    private javax.swing.JButton crearCuentaBtn;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton iniciarSesionBtn;
    private javax.swing.JTextField nombreUsuarioField;
    // End of variables declaration//GEN-END:variables
}
