package com.mycompany.fixya;

import javax.swing.*;

public class InicioSesionFrame extends JFrame {
    private Autenticacion auth;
    private JFrame CrearCuentaFrame;
    /**
     * Creates new form InicioSesion
     */
    public InicioSesionFrame() {
        this.CrearCuentaFrame = CrearCuentaFrame;
        auth = new Autenticacion();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        ContrasenaPasswordField = new javax.swing.JPasswordField();
        CrearCuentaBtn = new javax.swing.JButton();
        NombreUsuarioField = new javax.swing.JTextField();
        IniciarSesionBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(700, 400));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContrasenaPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContrasenaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaPasswordFieldActionPerformed(evt);
            }
        });
        background.add(ContrasenaPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 290, 50));

        CrearCuentaBtn.setBackground(new java.awt.Color(51, 51, 255));
        CrearCuentaBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        CrearCuentaBtn.setForeground(new java.awt.Color(255, 255, 255));
        CrearCuentaBtn.setText("Crear cuenta");
        CrearCuentaBtn.setToolTipText("");
        CrearCuentaBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CrearCuentaBtn.setBorderPainted(false);
        CrearCuentaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CrearCuentaBtnMousePressed(evt);
            }
        });
        CrearCuentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCuentaBtnActionPerformed(evt);
            }
        });
        background.add(CrearCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 220, 50));

        NombreUsuarioField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreUsuarioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreUsuarioFieldActionPerformed(evt);
            }
        });
        background.add(NombreUsuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 290, 50));

        IniciarSesionBtn.setBackground(new java.awt.Color(51, 51, 255));
        IniciarSesionBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        IniciarSesionBtn.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSesionBtn.setText("Iniciar sesión");
        IniciarSesionBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        IniciarSesionBtn.setBorderPainted(false);
        IniciarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionBtnActionPerformed(evt);
            }
        });
        background.add(IniciarSesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 220, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IniciarSesion.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionBtnActionPerformed
        // TODO add your handling code here:
        realizarLogin();
    }//GEN-LAST:event_IniciarSesionBtnActionPerformed

    private void CrearCuentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCuentaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearCuentaBtnActionPerformed

    private void CrearCuentaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCuentaBtnMousePressed
        // TODO add your handling code here:
        CrearCuentaFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_CrearCuentaBtnMousePressed

    private void NombreUsuarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreUsuarioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreUsuarioFieldActionPerformed

    private void ContrasenaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaPasswordFieldActionPerformed
    private void realizarLogin() {
        String usuario = NombreUsuarioField.getText();
        String contrasena = new String(ContrasenaPasswordField.getPassword());

        Usuario u = auth.iniciarSesion(usuario, contrasena);
        if (u != null) {
            JOptionPane.showMessageDialog(this, "Bienvenido " + u.getNombre());
            new MenuPrincipalFrame().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ContrasenaPasswordField;
    private javax.swing.JButton CrearCuentaBtn;
    private javax.swing.JButton IniciarSesionBtn;
    private javax.swing.JTextField NombreUsuarioField;
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
