package com.mycompany.fixya;


import javax.swing.JFrame;


public class MenuClienteFrame extends javax.swing.JFrame {
    private JFrame MenuPrincipal;
    /**
     * Creates new form MenuClienteFrame
     */
    public MenuClienteFrame() {
        initComponents();
        this.MenuPrincipal = MenuPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        CrearClienteBoton = new javax.swing.JButton();
        BuscarClienteBtn = new javax.swing.JButton();
        AgregarVisitaBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(0, 102, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        CrearClienteBoton.setBackground(new java.awt.Color(51, 102, 255));
        CrearClienteBoton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CrearClienteBoton.setForeground(new java.awt.Color(255, 255, 255));
        CrearClienteBoton.setText("Crear Cliente");
        CrearClienteBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CrearClienteBoton.setBorderPainted(false);
        CrearClienteBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CrearClienteBotonMousePressed(evt);
            }
        });
        CrearClienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearClienteBotonActionPerformed(evt);
            }
        });
        bg.add(CrearClienteBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 220, 50));

        BuscarClienteBtn.setBackground(new java.awt.Color(51, 102, 255));
        BuscarClienteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BuscarClienteBtn.setForeground(new java.awt.Color(255, 255, 255));
        BuscarClienteBtn.setText("Buscar Cliente");
        BuscarClienteBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BuscarClienteBtn.setBorderPainted(false);
        BuscarClienteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarClienteBtnMousePressed(evt);
            }
        });
        bg.add(BuscarClienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 220, 50));

        AgregarVisitaBtn.setBackground(new java.awt.Color(51, 102, 255));
        AgregarVisitaBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgregarVisitaBtn.setForeground(new java.awt.Color(255, 255, 255));
        AgregarVisitaBtn.setText("Agregar Visita");
        AgregarVisitaBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AgregarVisitaBtn.setBorderPainted(false);
        AgregarVisitaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AgregarVisitaBtnMousePressed(evt);
            }
        });
        AgregarVisitaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVisitaBtnActionPerformed(evt);
            }
        });
        bg.add(AgregarVisitaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 220, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clientes.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearClienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearClienteBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearClienteBotonActionPerformed

    private void CrearClienteBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearClienteBotonMousePressed
        new CrearClienteFrame().setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearClienteBotonMousePressed

    private void BuscarClienteBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarClienteBtnMousePressed
  new BuscarClienteFrame().setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarClienteBtnMousePressed

    private void AgregarVisitaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarVisitaBtnMousePressed
      new AgregarVisitaFrame().setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarVisitaBtnMousePressed

    private void AgregarVisitaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarVisitaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarVisitaBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuClienteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarVisitaBtn;
    private javax.swing.JButton BuscarClienteBtn;
    private javax.swing.JButton CrearClienteBoton;
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
