package com.mycompany.fixya;


import javax.swing.JFrame;


public class MenuClienteFrame extends javax.swing.JFrame {
    private JFrame MenuPrincipalFrame;
    /**
     * Creates new form MenuClienteFrame
     */
    public MenuClienteFrame() {
        this.MenuPrincipalFrame = new MenuPrincipalFrame();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        volverBtn = new javax.swing.JButton();
        crearClienteBtn = new javax.swing.JButton();
        agregarVisitaBtn = new javax.swing.JButton();
        buscarClienteBtn = new javax.swing.JButton();
        BuscarvisitaBtn = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(0, 102, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverBtn.setBackground(new java.awt.Color(102, 102, 102));
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("Volver");
        volverBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volverBtnMousePressed(evt);
            }
        });
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        bg.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        crearClienteBtn.setBackground(new java.awt.Color(51, 102, 255));
        crearClienteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        crearClienteBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearClienteBtn.setText("Crear Cliente");
        crearClienteBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crearClienteBtn.setBorderPainted(false);
        crearClienteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearClienteBtnMousePressed(evt);
            }
        });
        crearClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClienteBtnActionPerformed(evt);
            }
        });
        bg.add(crearClienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 220, 50));

        agregarVisitaBtn.setBackground(new java.awt.Color(51, 102, 255));
        agregarVisitaBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarVisitaBtn.setForeground(new java.awt.Color(255, 255, 255));
        agregarVisitaBtn.setText("Agregar Visita");
        agregarVisitaBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agregarVisitaBtn.setBorderPainted(false);
        agregarVisitaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarVisitaBtnMousePressed(evt);
            }
        });
        agregarVisitaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarVisitaBtnActionPerformed(evt);
            }
        });
        bg.add(agregarVisitaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 220, 50));

        buscarClienteBtn.setBackground(new java.awt.Color(51, 102, 255));
        buscarClienteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscarClienteBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarClienteBtn.setText("Buscar Cliente");
        buscarClienteBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarClienteBtn.setBorderPainted(false);
        buscarClienteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarClienteBtnMousePressed(evt);
            }
        });
        bg.add(buscarClienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 220, 50));

        BuscarvisitaBtn.setBackground(new java.awt.Color(51, 102, 255));
        BuscarvisitaBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BuscarvisitaBtn.setForeground(new java.awt.Color(255, 255, 255));
        BuscarvisitaBtn.setText("Buscar Visita");
        BuscarvisitaBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BuscarvisitaBtn.setBorderPainted(false);
        BuscarvisitaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarvisitaBtnMousePressed(evt);
            }
        });
        bg.add(BuscarvisitaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 220, 50));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clientes.png"))); // NOI18N
        bg.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void crearClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClienteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearClienteBtnActionPerformed

    private void crearClienteBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearClienteBtnMousePressed
        new CrearClienteFrame().setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_crearClienteBtnMousePressed

    private void BuscarvisitaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarvisitaBtnMousePressed
        new BuscarClienteFrame().setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarvisitaBtnMousePressed

    private void agregarVisitaBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarVisitaBtnMousePressed
      new AgregarVisitaFrame().setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarVisitaBtnMousePressed

    private void agregarVisitaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarVisitaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarVisitaBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverBtnActionPerformed

    private void volverBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverBtnMousePressed
          // TODO add your handling code here:
          MenuPrincipalFrame.setVisible(true);
          dispose();
    }//GEN-LAST:event_volverBtnMousePressed

    private void buscarClienteBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarClienteBtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarClienteBtnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuClienteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarvisitaBtn;
    private javax.swing.JButton agregarVisitaBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JButton buscarClienteBtn;
    private javax.swing.JButton crearClienteBtn;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
