/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fixya;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Tote
 */
public class MenuVehiculoFrame extends javax.swing.JFrame {
    private JFrame MenuPrincipalFrame;

    /**
     * Creates new form VehiculoJframe
     */
    public MenuVehiculoFrame() {
           initComponents();
    this.MenuPrincipalFrame = new MenuPrincipalFrame();
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        volverBtn = new javax.swing.JButton();
        crearVehiculoBtn = new javax.swing.JButton();
        buscarVehiculoBtn = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setPreferredSize(new java.awt.Dimension(800, 800));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverBtn.setBackground(new java.awt.Color(102, 102, 102));
        volverBtn.setForeground(new java.awt.Color(255, 255, 255));
        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        bg.add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        crearVehiculoBtn.setBackground(new java.awt.Color(51, 102, 255));
        crearVehiculoBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        crearVehiculoBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearVehiculoBtn.setText("Crear Vehículo");
        crearVehiculoBtn.setToolTipText("");
        crearVehiculoBtn.setBorderPainted(false);
        crearVehiculoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearVehiculoBtnActionPerformed(evt);
            }
        });
        bg.add(crearVehiculoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 220, 50));

        buscarVehiculoBtn.setBackground(new java.awt.Color(51, 102, 255));
        buscarVehiculoBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        buscarVehiculoBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarVehiculoBtn.setText("Buscar Vehículo");
        buscarVehiculoBtn.setBorderPainted(false);
        buscarVehiculoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarVehiculoBtnActionPerformed(evt);
            }
        });
        bg.add(buscarVehiculoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 220, 50));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vehiculo.png"))); // NOI18N
        bg.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
        MenuPrincipalFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void crearVehiculoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearVehiculoBtnActionPerformed
        // TODO add your handling code here:
        new CrearVehiculoFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_crearVehiculoBtnActionPerformed

    private void buscarVehiculoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarVehiculoBtnActionPerformed
        // TODO add your handling code here:
        new BuscarVehiculoFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buscarVehiculoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVehiculoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVehiculoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVehiculoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVehiculoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVehiculoFrame().setVisible(true);
            }
        });
    }
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton buscarVehiculoBtn;
    private javax.swing.JButton crearVehiculoBtn;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
