/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fixya;
import javax.swing.*;

public class MenuPrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        LogoClinete = new javax.swing.JLabel();
        LogoVehiculo = new javax.swing.JLabel();
        LogoOrden = new javax.swing.JLabel();
        MenuCLienteBoton = new javax.swing.JButton();
        MenuVehiculoBoton = new javax.swing.JButton();
        MenuOrdenes = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BG.setBackground(new java.awt.Color(0, 102, 204));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoClinete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoCLiente.png"))); // NOI18N
        BG.add(LogoClinete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, 170));

        LogoVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoVehiculo.png"))); // NOI18N
        BG.add(LogoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 210, 170));

        LogoOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoOrden.png"))); // NOI18N
        BG.add(LogoOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 200, 170));

        MenuCLienteBoton.setBackground(new java.awt.Color(153, 204, 255));
        MenuCLienteBoton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuCLienteBoton.setText("Menu Clientes");
        MenuCLienteBoton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenuCLienteBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuCLienteBotonMousePressed(evt);
            }
        });
        MenuCLienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCLienteBotonActionPerformed(evt);
            }
        });
        BG.add(MenuCLienteBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 130, 30));

        MenuVehiculoBoton.setBackground(new java.awt.Color(153, 204, 255));
        MenuVehiculoBoton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuVehiculoBoton.setText("Menu Vehiculos");
        MenuVehiculoBoton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenuVehiculoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuVehiculoBotonMousePressed(evt);
            }
        });
        BG.add(MenuVehiculoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 120, 30));

        MenuOrdenes.setBackground(new java.awt.Color(153, 204, 255));
        MenuOrdenes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuOrdenes.setText("Menu Ordenes");
        MenuOrdenes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenuOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuOrdenesMousePressed(evt);
            }
        });
        BG.add(MenuOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 120, 30));

        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuprincipalLogo.png"))); // NOI18N
        Titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BG.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 300, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCLienteBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCLienteBotonMousePressed
        // TODO add your handling code here:
        new MenuClienteFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_MenuCLienteBotonMousePressed

    private void MenuCLienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCLienteBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCLienteBotonActionPerformed

    private void MenuVehiculoBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuVehiculoBotonMousePressed
        // TODO add your handling code here:
       new MenuVehiculoFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_MenuVehiculoBotonMousePressed

    private void MenuOrdenesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuOrdenesMousePressed
        // TODO add your handling code here:
        new MenuOrdenesFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_MenuOrdenesMousePressed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel LogoClinete;
    private javax.swing.JLabel LogoOrden;
    private javax.swing.JLabel LogoVehiculo;
    private javax.swing.JButton MenuCLienteBoton;
    private javax.swing.JButton MenuOrdenes;
    private javax.swing.JButton MenuVehiculoBoton;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
