/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fixya;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Tote
 */
public class RegistrarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarVehiculp
     */
    public RegistrarVehiculo() {
          initComponents();
    
    
    // Pantalla completa CON bordes (funciona siempre)
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
    // Quitar imagen fija y cargar imagen escalada
    //jLabel2.setIcon(null);
    
    javax.swing.SwingUtilities.invokeLater(() -> {
        SetImageLabel(RegistrarVehiculo, "/Registrarvehiculo.png");
    });
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FabricanteTXT = new javax.swing.JTextField();
        ModeloTXT = new javax.swing.JTextField();
        RegistrarVehiculo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FabricanteTXT.setBackground(new java.awt.Color(204, 204, 255));
        FabricanteTXT.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        FabricanteTXT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        FabricanteTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        FabricanteTXT.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        FabricanteTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FabricanteTXTActionPerformed(evt);
            }
        });
        jPanel1.add(FabricanteTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 690, 80));
        FabricanteTXT.getAccessibleContext().setAccessibleName("");
        FabricanteTXT.getAccessibleContext().setAccessibleDescription("");

        ModeloTXT.setBackground(new java.awt.Color(204, 204, 255));
        ModeloTXT.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        ModeloTXT.setBorder(null);
        ModeloTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeloTXTActionPerformed(evt);
            }
        });
        jPanel1.add(ModeloTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 690, 80));

        RegistrarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RegistrarVehiculo.png"))); // NOI18N
        jPanel1.add(RegistrarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1961, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FabricanteTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FabricanteTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FabricanteTXTActionPerformed

    private void ModeloTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeloTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModeloTXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarVehiculo().setVisible(true);
            }
        });
    }
    
        private void SetImageLabel(JLabel labelName, String root){
    ImageIcon image = new ImageIcon(getClass().getResource(root));
    Icon icon = new ImageIcon(image.getImage().getScaledInstance(
        labelName.getWidth(), 
        labelName.getHeight(), 
        Image.SCALE_FAST));
    labelName.setIcon(icon);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FabricanteTXT;
    private javax.swing.JTextField ModeloTXT;
    private javax.swing.JLabel RegistrarVehiculo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
