/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fixya;

/**
 *
 * @author PC
 */
public class VerTrabajosPorOrdenFrame extends javax.swing.JFrame {
    private OrdenDAO ordenDAO = new OrdenDAO();
    private TrabajoDAO trabajoDAO = new TrabajoDAO();
    /**
     * Creates new form VerTrabajosPorOrdenFrame
     */
    public VerTrabajosPorOrdenFrame() {
        this.ordenDAO = ordenDAO;
        this.trabajoDAO = trabajoDAO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        ordenIdField = new javax.swing.JTextField();
        verTrabajosBtn = new javax.swing.JButton();
        chapaField = new javax.swing.JTextField();
        buscarOrdenBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordenesTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        trabajosTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1020, 570));

        bg.setPreferredSize(new java.awt.Dimension(1020, 570));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg.add(ordenIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 150, 50));

        verTrabajosBtn.setBackground(new java.awt.Color(51, 102, 255));
        verTrabajosBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        verTrabajosBtn.setForeground(new java.awt.Color(255, 255, 255));
        verTrabajosBtn.setText("Ver trabajos");
        verTrabajosBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verTrabajosBtn.setBorderPainted(false);
        verTrabajosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTrabajosBtnActionPerformed(evt);
            }
        });
        bg.add(verTrabajosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 160, 40));
        bg.add(chapaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 180, 50));

        buscarOrdenBtn.setBackground(new java.awt.Color(51, 102, 255));
        buscarOrdenBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        buscarOrdenBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarOrdenBtn.setText("Buscar orden");
        buscarOrdenBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarOrdenBtn.setBorderPainted(false);
        buscarOrdenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarOrdenBtnActionPerformed(evt);
            }
        });
        bg.add(buscarOrdenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TrabajosDeLaOrden.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ordenesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ordenesTable);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 310, 140));

        trabajosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(trabajosTable);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 321, 510, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verTrabajosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTrabajosBtnActionPerformed
        // TODO add your handling code here:
        verTrabajos();
    }//GEN-LAST:event_verTrabajosBtnActionPerformed

    private void buscarOrdenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarOrdenBtnActionPerformed
        // TODO add your handling code here:
        buscarOrden();
    }//GEN-LAST:event_buscarOrdenBtnActionPerformed
    
    private void buscarOrden(){
        String chapa = chapaField.getText();
        ordenDAO.buscarOrdenSimple(chapa,ordenesTable);
    }
    
    private void verTrabajos(){
        String ordenIdString = ordenIdField.getText();
        int ordenId = Integer.parseInt(ordenIdString);
        trabajoDAO.verTrabajos(ordenId,trabajosTable);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerTrabajosPorOrdenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerTrabajosPorOrdenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerTrabajosPorOrdenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerTrabajosPorOrdenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerTrabajosPorOrdenFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton buscarOrdenBtn;
    private javax.swing.JTextField chapaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField ordenIdField;
    private javax.swing.JTable ordenesTable;
    private javax.swing.JTable trabajosTable;
    private javax.swing.JButton verTrabajosBtn;
    // End of variables declaration//GEN-END:variables
}
